# Generated by Django 2.0.6 on 2018-06-22 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0001_initial'),
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='dni_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almacen.Almacen'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='dni_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='guia_remision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almacen.GuiaRemision'),
        ),
        migrations.AddField(
            model_name='guiaremision',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almacen.Proveedor'),
        ),
        migrations.AddField(
            model_name='detallestock',
            name='id_almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almacen.Almacen'),
        ),
        migrations.AddField(
            model_name='detallestock',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.Producto'),
        ),
        migrations.AddField(
            model_name='detallesalida',
            name='codigo_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.Producto'),
        ),
        migrations.AddField(
            model_name='detallesalida',
            name='id_almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almacen.Almacen'),
        ),
        migrations.AddField(
            model_name='detallesalida',
            name='id_salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almacen.Salida'),
        ),
        migrations.AddField(
            model_name='detalleingreso',
            name='codigo_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.Producto'),
        ),
        migrations.AddField(
            model_name='detalleingreso',
            name='id_ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almacen.Ingreso'),
        ),
        migrations.AddField(
            model_name='detalleingreso',
            name='unidad_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.UnidadMedicion'),
        ),
        migrations.AddField(
            model_name='detallealmacen',
            name='codigo_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.Producto'),
        ),
        migrations.AddField(
            model_name='detallealmacen',
            name='id_almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almacen.Almacen'),
        ),
        migrations.AddField(
            model_name='detallealmacen',
            name='id_ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almacen.Ingreso'),
        ),
    ]
